### ISSUE TITLE
Support Windows cells to allow .NET app deployments

### ISSUE THREAD

**Issue by cdelashmutt-pivotal** [pivotal-cf/pcfdev#19]
It would be great if we had a systematic way to enable micropcf to allow Windows Cells to be added to it to allow hosting for .NET applications.

I am able to do this today (manually, and somewhat unreliably) if I create a separate Windows 2012R2 VM, use the GardenWindows.msi and DiegoWindows.msi from network.pivotal.com, and point them to the 172.x.x.x address that micropcf is running on for Consul and etcd.  Additionally, I need to modify the config of cloud_controller_ng to add a section to the stacks.yml to enable the windows2012R2 stack:
```yaml
default: cflinuxfs2
stacks: 
- description: Cloud Foundry Linux-based filesystem
  name: cflinuxfs2
- description: Windows Server 2012 R2
  name: windows2012R2
```

It would be really cool if there was an option to either enable this stack when the box is being configured, or perhaps even make it the default in the config file for ccng.
